backend:
  name: github
  repo: rapsamaniego27/music-profile
  branch: master

media_folder: "assets/files"

# Basic setup for collections
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "_data/home.yml"
      fields:
      - label: "Welcome Tagline"
        name: "welcome_tagline"
        widget: "string"
      - label: "Welcome Subtext"
        name: "welcome_subtext"
        widget: "string"
      - label: "Summary Title"
        name: "summary_title"
        widget: "string"
      - label: "Summary Description"
        name: "summary_description"
        widget: "text"
      - label: "Summary Image"
        name: "summary_image"
        widget: "image"
      - label: "Summary Link"
        name: "summary_link"
        widget: "string"
      - label: "Feature Left Title"
        name: "feature_left_title"
        widget: "string"
      - label: "Feature Left Description"
        name: "feature_left_description"
        widget: "text"
      - label: "Feature Left Image (624 x 180)"
        name: "feature_left_image"
        widget: "image"
      - label: "Feature Left Link"
        name: "feature_left_link"
        widget: "string"
      - label: "Feature Right Title"
        name: "feature_right_title"
        widget: "string"
      - label: "Feature Right Description"
        name: "feature_right_description"
        widget: "text"
      - label: "Feature Right Image (624 x 180)"
        name: "feature_right_image"
        widget: "image"
      - label: "Feature Right Link"
        name: "feature_right_link"
        widget: "string"
    - label: "Bio" #Bio
      name: "bio"
      file: "_data/bio.yml"
      create: true
      fields:
      - label: "Blocks"
        name: "blocks"
        widget: "list"
        required: false
        fields:
        - label: "alignment"
          name: "alignment"
          widget: "select"
          options: ["one column", "two columns", "two columns reverse"]
          default: ["one column"]
        - label: "Content"
          name: "content"
          widget: "object"
          required: false
          fields: 
          - label: Text (300 - 420 for 2 columns)
            name: text
            widget: markdown
          - label: Image(280 x 194)
            name: image
            widget: image
            required: false
      


  - label: "Metas" # Page Metas
    name: "metas"
    create: true
    folder: "_metas"
    fields:
    - label: "Title"
      name: "title"
      widget: "string"
    - label: "Meta Description"
      name: "meta_description"
      widget: "text"
    - label: "Slug"
      name: "slug"
      widget: "string"
    - label: "Permalink"
      name: "permalink"
      widget: "string"
    - label: "Meta Image"
      name: "meta_image"
      widget: "image"
      required: false


