backend:
  name: github
  repo: rapsamaniego27/music-profile

media_folder: "assets/files"

# Basic setup for collections
collections:
  - name: "pages"
  - label: "Pages"
  - create: true
  - files:
    - label: "Home"
    - name: "home"
    - file: "_data/home.yml"
    - fields:
      - label: "Welcome Tagline"
      - name: "welcome_tagline"
      - widget: "string"
      - label: "Welcome Subtext"
      - name: "welcome_subtext"
      - widget: "string"

      
