backend:
  name: github
  repo: rapsamaniego27/music-profile

media_folder: "assets/files"

collections:
  - label: "Pages"
    name: "pages"
    create: true
    folder: "_pages"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Meta Description"
        name: "meta_description"
        widget: "text"
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Permalink"
        name: "permalink"
        widget: "string"
      - label: "Meta Image"
        name: "meta_image"
        widget: "image"
        required: false