backend:
  name: github
  repo: rapsamaniego27/music-profile
  branch: master

media_folder: "assets/files"

# Basic setup for collections
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "_data/home.yml"
      fields:
      - label: "Welcome Tagline"
        name: "welcome_tagline"
        widget: "string"
      - label: "Welcome Subtext"
        name: "welcome_subtext"
        widget: "string"


  - label: "Metas"
    name: "metas"
    create: true
    folder: "_metas"
    fields:
    - label: "Title"
      name: "title"
      widget: "string"
    - label: "Meta Description"
      name: "meta_description"
      widget: "text"
    - label: "Slug"
      name: "slug"
      widget: "string"
    - label: "Permalink"
      name: "permalink"
      widget: "string"
    - label: "Meta Image"
      name: "meta_image"
      widget: "image"
      required: false
      
